# Generated by Django 4.2.5 on 2023-09-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='time',
        ),
    ]
