# Generated by Django 4.2.5 on 2023-09-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': ' Doctor', 'verbose_name_plural': 'Doctors'},
        ),
    ]
